In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
train_data = pd.read_csv('/kaggle/input/competitions/titanic/train.csv')
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
train_data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
test_data = pd.read_csv('/kaggle/input/competitions/titanic/test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
test_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
test_data.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
X = train_data[['Pclass', 'Sex', 'Fare']]
y = train_data['Survived']
X

     Pclass     Sex     Fare
0         3    male   7.2500
1         1  female  71.2833
2         3  female   7.9250
3         1  female  53.1000
4         3    male   8.0500
..      ...     ...      ...
886       2    male  13.0000
887       1  female  30.0000
888       3  female  23.4500
889       1    male  30.0000
890       3    male   7.7500

[891 rows x 3 columns]

In [9]:
#文字列の変換
X = pd.get_dummies(X, columns=['Pclass', 'Sex'])
X

        Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male
0     7.2500     False     False      True       False      True
1    71.2833      True     False     False        True     False
2     7.9250     False     False      True        True     False
3    53.1000      True     False     False        True     False
4     8.0500     False     False      True       False      True
..       ...       ...       ...       ...         ...       ...
886  13.0000     False      True     False       False      True
887  30.0000      True     False     False        True     False
888  23.4500     False     False      True        True     False
889  30.0000      True     False     False       False      True
890   7.7500     False     False      True       False      True

[891 rows x 6 columns]

In [10]:
#fareのスケーリング
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X)

MinMaxScaler()

In [11]:
X_scaled = scaler.transform(X)
X = pd.DataFrame(X_scaled, columns=X.columns)
X.head()

       Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male
0  0.014151       0.0       0.0       1.0         0.0       1.0
1  0.139136       1.0       0.0       0.0         1.0       0.0
2  0.015469       0.0       0.0       1.0         1.0       0.0
3  0.103644       1.0       0.0       0.0         1.0       0.0
4  0.015713       0.0       0.0       1.0         0.0       1.0

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [13]:
lr.score(X_test, y_test)

0.7877094972067039

In [14]:
X_for_submit = test_data[['Pclass', 'Sex', 'Fare']]
X_for_submit = pd.get_dummies(X_for_submit, columns=['Pclass', 'Sex'])
X_for_submit_scaled = scaler.transform(X_for_submit)
X_for_submit_scaled

array([[0.01528158, 0.        , 0.        , 1.        , 0.        ,
        1.        ],
       [0.01366309, 0.        , 0.        , 1.        , 1.        ,
        0.        ],
       [0.01890874, 0.        , 1.        , 0.        , 0.        ,
        1.        ],
       ...,
       [0.01415106, 0.        , 0.        , 1.        , 0.        ,
        1.        ],
       [0.01571255, 0.        , 0.        , 1.        , 0.        ,
        1.        ],
       [0.0436405 , 0.        , 0.        , 1.        , 0.        ,
        1.        ]])

In [15]:
X_for_submit = pd.DataFrame(X_for_submit_scaled, columns=X_for_submit.columns)
X_for_submit

         Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male
0    0.015282       0.0       0.0       1.0         0.0       1.0
1    0.013663       0.0       0.0       1.0         1.0       0.0
2    0.018909       0.0       1.0       0.0         0.0       1.0
3    0.016908       0.0       0.0       1.0         0.0       1.0
4    0.023984       0.0       0.0       1.0         1.0       0.0
..        ...       ...       ...       ...         ...       ...
413  0.015713       0.0       0.0       1.0         0.0       1.0
414  0.212559       1.0       0.0       0.0         1.0       0.0
415  0.014151       0.0       0.0       1.0         0.0       1.0
416  0.015713       0.0       0.0       1.0         0.0       1.0
417  0.043640       0.0       0.0       1.0         0.0       1.0

[418 rows x 6 columns]

In [16]:
X_for_submit['Fare'] = X_for_submit['Fare'].fillna(X_for_submit['Fare'].median())

In [17]:
submit = test_data[['PassengerId']].copy()
submit['Survived'] = lr.predict(X_for_submit)
submit

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [18]:
submit.to_csv('submission.csv', index=False)